---
 out_dir: './results/run_38_char/'
 dataset_dir: "./dataset/CHO_only2.smi" 
 which_vocab: "selfies" # "selfies", "regex", or "char"
 vocab_path: "./vocab/CHO_only.yaml"
 percentage: 1

 rnn_config:
  # size of vocab + <eos> + <sos> + <pad> 
  # char: 48, regex:75, selfies:78
  num_embeddings: 28
  embedding_dim: 256
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 10
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001