---
 out_dir: './run/task1/'
 dataset_dir: "./dataset/molecules_cleaned.smi" 
 which_vocab: "selfies" # "selfies", "regex", or "char"
 vocab_path: "./vocab/selfies.yaml"
 percentage: 1

 rnn_config:
  # size of vocab + <eos> + <sos> + <pad> 
  # char: 48, regex:75, selfies:78
  num_embeddings: 28
  embedding_dim: 256
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 200
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001
